version: "3.9"
services:
  mysql:
    image: "mysql/mysql-server:8.0"
#    image: "mysql:8.0"
    container_name: "mysql-8.0"
    hostname: "mysql-8.0"
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - "/mysql-db/mysql-13/data:/var/lib/mysql"
      - "/mysql-db/mysql-13/etc/my.cnf:/etc/my.cnf"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
