version: "3.9"
services:
  postgres:
    image: "postgres:12.12"
    container_name: "postgres-12"
    hostname: "postgres-12"
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - "/06-db-02-sql/postgres/data:/var/lib/postgresql/data"
      - "/06-db-02-sql/postgres/backup:/pgbackup"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_PASSWORD=12345
      # - POSTGRES_USER=vagrant
