---
all:
  hosts:
    jenkins-master:
      ansible_host: 51.250.12.50
    jenkins-agent:
      ansible_host: 51.250.8.251
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master:
        jenkins_agents:
          hosts:
              jenkins-agent:
  vars:
    ansible_connection_type: paramiko
    ansible_user: duxaxa